name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on pushes to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install testing framework

      - name: Run tests
        run: pytest  # Run the tests

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Run only if build-and-test succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy (Simulated)
        run: echo "Deploying to production..."  # Simulate deployment
